---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "ccai"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "floods-backend"
  namespace: "ccai"
  labels:
    app: "floods-backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "floods-backend"
  template:
    metadata:
      labels:
        app: "floods-backend"
    spec:
      containers:
      - name: "floods-backend"
        image: "gcr.io/mila-ccai/floods-backend:97a2f3fab2cfa55656a8da3fddba120a5880334a"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "floods-backend-hpa"
  namespace: "ccai"
  labels:
    app: "floods-backend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "floods-backend"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: floods-backend-service
  namespace: ccai
  labels:
    app: floods-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: floods-backend
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.247.109.48