version: 2
jobs:
  build:
    docker:
      - image: python:3.7-alpine
    working_directory: /floods-backend
    steps: &steps
      - checkout
      - run: apk add build-base
      - run: pip install -r requirements.txt
      - run: make test
workflows:
  version: 2
  build:
    jobs:
      - build