apiVersion: v1
kind: Service
metadata:
  name: floods-backend-service
  namespace: ccai
  labels:
    app: floods-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: floods-backend
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.196.115.157
